name: Docker Build and Push

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Login en GitHub Container Registry (GHCR)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: cquintasp  # Usamos el nombre de usuario de GitHub
        password: ${{ secrets.GH_PAT }}  # Usamos el token de GitHub preconfigurado

    # 3. Construir la imagen Docker
    - name: Build Docker image
      run: docker build --no-cache -t ghcr.io/cquintasp/java-docker-hello-world:latest .

    # 4. Subir la imagen al registro de GitHub Container Registry (GHCR)
    - name: Push Docker image to GHCR
      run: docker push ghcr.io/cquintasp/java-docker-hello-worl:latest
