name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3


    # 3. Construir la imagen Docker
    - name: Build Docker image
      run: |
       docker login --username cquintasp --password ${{DOCKER_PASSWORD }} ghcr.io
       docker build -t ${{ secrets.DOCKER_USERNAME }}/java-docker-hello-world:latest .

    # 4. Subir la imagen al registro Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/java-docker-hello-world:latest
