name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Login en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: cquintasp
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Construir la imagen Docker
    - name: Build Docker image
      run: docker build --no-cache -t cquintasp/java-docker-hello-world:latest .

    # 4. Subir la imagen al registro Docker Hub
    - name: Push Docker image
      run: docker push cquintasp/java-docker-hello-world:latest
